### ISSUE TITLE
[SFT error] After SFT the released LEGO-7B model on our data, the model suffer from "RuntimeError: probability tensor contains either `inf`, `nan` or element < 0"

### ISSUE THREAD

**Issue by cool-xuan** [lzw-lzw/GroundingGPT#10]
Thanks for your model release. When we try to SFT the LEGO-7B on our own data, the fine-tuned model is unable to generate the answer but encounter
```
Assistant: Traceback (most recent call last):
  File "/workspace/GroundingGPT/lego/evaluate/videoOnly-cli.py", line 100, in <module>
    response = single_process(args, model_bag)
  File "/workspace/GroundingGPT/lego/evaluate/videoOnly-cli.py", line 59, in single_process
    output_ids = model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2770, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
We have try many tips such as set `model.bfloat16()` or disable `do_sample`.
In particular, when we disable `do_sample`, the model outputs nothing but `<unk>`.

Our training shell is totally following the `finetune.sh`, which is 
```
deepspeed --master_port 9826 --include="localhost:1,2,3,4,5,6" \
    lego/train/train.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path ckpt/GroundingGPT-7B\
    --data_path data/ownDatas/conversations_train.json \
    --video_folder data/ownData/\
    --tune_mm_mlp_adapter False\
    --vision_tower ckpt/clip-vit-large-patch14-336\
    --mm_vision_select_layer -2\
    --mm_use_im_start_end True\
    --image_aspect_ratio pad\
    --bf16 True\
    --fp16 False\
    --output_dir ./workdirs/debug\
    --num_train_epochs 1\
    --per_device_train_batch_size 32\
    --per_device_eval_batch_size 4\
    --gradient_accumulation_steps 1\
    --evaluation_strategy "no"\
    --save_strategy "steps"\
    --save_steps 500\
    --save_total_limit 2\
    --learning_rate 2e-5\
    --weight_decay 0.\
    --warmup_ratio 0.03\
    --lr_scheduler_type cosine\
    --logging_steps 1\
    --tf32 True\
    --model_max_length 2048\
    --gradient_checkpointing True\
    --lazy_preprocess True\
    --report_to wandb
```

The training process is okay, and the official LEGO-7B model is able to generate answers with our inference code. 

If there any advice for us to try?

**Comment by lzw-lzw** [comment]
Hello, if SFT can be trained successfully without any errors during the training process, the issue might be related to the dtype used when loading the model during inference. You can try converting the model to the bf16 precision format . For more details, you can refer to the following link: https://github.com/meta-llama/llama/issues/380

**Comment by cool-xuan** [comment]
> Hello, if SFT can be trained successfully without any errors during the training process, the issue might be related to the dtype used when loading the model during inference. You can try converting the model to the bf16 precision format . For more details, you can refer to the following link: [meta-llama/llama#380](https://github.com/meta-llama/llama/issues/380)

Thanks for your rapid reply. Unfortunately, we have tried this but no work. T.T

**Comment by lzw-lzw** [comment]
Can you try infering with the cli.py we provided and your weights？

**Comment by cool-xuan** [comment]
> Can you try infering with the cli.py we provided and your weights？

Yes, our inference code is based on cli.py. It is enable to generate with your LEGO-7B weights but not our SFT weights.

**Comment by cool-xuan** [comment]
When I check the training log, I find the Qformer and llama_proj weights are not frozen as your settings:
```
def initialize_video_sound_modules(
        self, 
        model_args=None, 
        freeze_vit=True, 
        freeze_qformer=True,
        llama_proj_model=None,
        frozen_llama_proj=False,
        frozen_video_Qformer=False,
        frozen_audio_Qformer=False,
        ):
```
While in Video-LLama, all these are frozen like: 
```
frozen_llama_proj=True,
frozen_video_Qformer=True,
frozen_audio_Qformer=True,
```

Is this may cause the problem?

**Comment by lzw-lzw** [comment]
I think this is not the question, could you please provide the infer code you use and your environments?

**Comment by cool-xuan** [comment]
The environment list :
```
Package                   Version
------------------------- ------------------
accelerate                0.30.1
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
asttokens                 2.0.5
astunparse                1.6.3
async-timeout             4.0.3
attrs                     23.1.0
audioread                 3.0.1
av                        12.0.0
backcall                  0.2.0
beautifulsoup4            4.12.2
blessed                   1.20.0
boltons                   23.0.0
braceexpand               0.1.7
brotlipy                  0.7.0
certifi                   2023.7.22
cffi                      1.15.1
chardet                   4.0.0
charset-normalizer        2.0.4
click                     8.0.4
cmake                     3.29.3
conda                     23.9.0
conda-build               3.27.0
conda-content-trust       0.2.0
conda_index               0.3.0
conda-libmamba-solver     23.7.0
conda-package-handling    2.2.0
conda_package_streaming   0.9.0
contourpy                 1.2.1
cryptography              41.0.3
cycler                    0.12.1
decorator                 5.1.1
decord                    0.6.0
deepspeed                 0.14.2
dnspython                 2.4.2
docker-pycreds            0.4.0
einops                    0.8.0
email_validator           2.1.1
exceptiongroup            1.0.4
executing                 0.8.3
expecttest                0.1.6
fastapi                   0.111.0
fastapi-cli               0.0.3
ffmpy                     0.3.2
filelock                  3.9.0
flash-attn                2.5.8
fonttools                 4.51.0
frozenlist                1.4.1
fsspec                    2023.9.2
ftfy                      6.2.0
fvcore                    0.1.5.post20221221
gitdb                     4.0.11
GitPython                 3.1.43
gmpy2                     2.1.2
gpustat                   1.1.1
gradio                    3.23.0
h11                       0.12.0
hjson                     3.1.0
httpcore                  0.15.0
httptools                 0.6.1
httpx                     0.23.0
huggingface-hub           0.16.4
hypothesis                6.87.2
idna                      3.4
imageio                   2.34.1
iopath                    0.1.10
ipython                   8.15.0
jedi                      0.18.1
Jinja2                    3.1.2
joblib                    1.4.2
jsonpatch                 1.32
jsonpointer               2.1
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lazy_loader               0.4
libarchive-c              2.9
libmambapy                1.4.1
librosa                   0.10.2
linkify-it-py             2.0.3
lit                       18.1.4
llvmlite                  0.42.0
markdown-it-py            2.2.0
markdown2                 2.4.13
MarkupSafe                2.1.1
matplotlib                3.8.4
matplotlib-inline         0.1.6
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
more-itertools            8.12.0
mpmath                    1.3.0
msgpack                   1.0.8
multidict                 6.0.5
networkx                  3.1
ninja                     1.11.1.1
numba                     0.59.1
numpy                     1.26.0
nvidia-cublas-cu11        11.10.3.66
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu11         8.5.0.96
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu11         10.9.0.58
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu11        10.2.10.91
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu11      11.7.4.91
nvidia-cusparse-cu12      12.1.0.106
nvidia-ml-py              12.550.52
nvidia-nccl-cu11          2.14.3
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.4.127
nvidia-nvtx-cu11          11.7.91
nvidia-nvtx-cu12          12.1.105
omegaconf                 2.3.0
opencv-python             4.9.0.80
orjson                    3.10.3
packaging                 23.1
pandas                    2.2.2
parameterized             0.9.0
parso                     0.8.3
peft                      0.6.2
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    10.0.1
pip                       23.2.1
pkginfo                   1.9.6
platformdirs              4.2.1
pluggy                    1.0.0
pooch                     1.8.1
portalocker               2.8.2
prettytable               3.10.0
prompt-toolkit            3.0.36
protobuf                  4.25.3
psutil                    5.9.0
ptyprocess                0.7.0
pure-eval                 0.2.2
py-cpuinfo                9.0.0
pycocotools               2.0.7
pycosat                   0.6.6
pycparser                 2.21
pydantic                  2.7.1
pydantic_core             2.18.2
pydub                     0.25.1
Pygments                  2.15.1
pynvml                    11.5.0
pyOpenSSL                 23.2.0
pyparsing                 3.1.2
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-etcd               0.4.5
python-multipart          0.0.9
pytorchvideo              0.1.5
pytz                      2023.3.post1
PyYAML                    6.0
referencing               0.35.1
regex                     2024.5.10
requests                  2.31.0
rfc3986                   1.5.0
rich                      13.7.1
rpds-py                   0.18.1
ruamel.yaml               0.17.21
ruamel.yaml.clib          0.2.6
safetensors               0.4.3
scikit-image              0.23.2
scikit-learn              1.4.2
scipy                     1.13.0
semantic-version          2.10.0
sentencepiece             0.2.0
sentry-sdk                2.1.1
setproctitle              1.3.3
setuptools                68.0.0
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sortedcontainers          2.4.0
soundfile                 0.12.1
soupsieve                 2.5
soxr                      0.3.7
stack-data                0.2.0
starlette                 0.37.2
svgwrite                  1.4.3
sympy                     1.11.1
tabulate                  0.9.0
termcolor                 2.4.0
threadpoolctl             3.5.0
tifffile                  2024.5.10
timm                      0.9.16
tokenizers                0.14.0
tomli                     2.0.1
toolz                     0.12.0
torch                     2.1.0
torchaudio                2.1.0
torchelastic              0.2.2
torchvision               0.16.0
tqdm                      4.65.0
traitlets                 5.7.1
transformers              4.34.0
triton                    2.1.0
truststore                0.8.0
typer                     0.12.3
types-dataclasses         0.6.6
typing_extensions         4.11.0
tzdata                    2024.1
uc-micro-py               1.0.3
ujson                     5.10.0
urllib3                   1.26.16
uvicorn                   0.29.0
uvloop                    0.19.0
wandb                     0.17.0
watchfiles                0.21.0
wavedrom                  2.0.3.post3
wcwidth                   0.2.13
webdataset                0.2.86
websockets                12.0
wheel                     0.41.2
yacs                      0.1.8
yarl                      1.9.4
zstandard                 0.19.0
```

Since only one modal (video) is required. The inference code is changed to:
```
import argparse
import torch
import sys
sys.path.append('/workspace/GroundingGPT')
from lego.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN, DEFAULT_VIDEO_TOKEN, DEFAULT_SOUND_TOKEN
from lego.conversation import SeparatorStyle
from lego import conversation as conversation_lib
from lego.mm_utils import tokenizer_image_token, KeywordsStoppingCriteria, load_image_square, postprocess_output
from lego.model.builder import CONFIG, load_pretrained_model
from video_llama.processors.video_processor import load_video
from video_llama.models.ImageBind.data import load_and_transform_audio_data
from lego.constants import DEFAULT_IMAGE_PATCH_TOKEN, DEFAULT_IMAGE_START_TOKEN, DEFAULT_IMAGE_END_TOKEN, DEFAULT_VIDEO_PATCH_TOKEN, \
                           DEFAULT_VIDEO_START_TOKEN, DEFAULT_VIDEO_END_TOKEN, DEFAULT_SOUND_PATCH_TOKEN, DEFAULT_SOUND_START_TOKEN, DEFAULT_SOUND_END_TOKEN

def single_process(args, model_bag):
    model, tokenizer, image_processor, video_transform, context_len = model_bag
    model = model.bfloat16()
    conv = conversation_lib.default_conversation.copy()
    roles = conv.roles
    image_path = None
    image_tensor = None
    video_tensor = None
    sound_tensor = None
    image = None
    try :
        video_path = args.video_file
        video = load_video(
                video_path = video_path,
                n_frms = model.config.max_frame,
                height = 224,
                width = 224,
                sampling ="uniform", return_msg = False)
        video_tensor = video_transform(video).unsqueeze(0).to(CONFIG.device, dtype=torch.bfloat16)
        inp = f"{roles[0]}: Can you give me the start and end times of the dance in the video?"
    except:
        print('Please input a correct video path.')

    print(f"{roles[1]}: ", end="")
    if video is not None:
        if model.config.mm_use_im_start_end:
            inp = DEFAULT_VIDEO_START_TOKEN + DEFAULT_VIDEO_PATCH_TOKEN * CONFIG.video_token_len + DEFAULT_VIDEO_END_TOKEN + '\n' + inp
        else:
            inp = DEFAULT_VIDEO_TOKEN + '\n' + inp
        conv.append_message(conv.roles[0], inp)
        video = None

    
    conv.append_message(conv.roles[1], None)
    prompt = conv.get_prompt()
    input_ids = tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors='pt').unsqueeze(0).cuda()
    stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
    keywords = [stop_str]
    stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)

    with torch.inference_mode():
        output_ids = model.generate(
            input_ids,
            images=image_tensor,
            videos=video_tensor,
            sounds=sound_tensor,
            do_sample=True,
            temperature=args.temperature,
            max_new_tokens=args.max_new_tokens, 
            use_cache=True,
            stopping_criteria=[stopping_criteria])
    
    outputs = tokenizer.decode(output_ids[0, input_ids.shape[1]:]).strip()
    if image_path is not None:
        outputs = postprocess_output(outputs, image_path)
    if outputs.endswith(stop_str):
        outputs = outputs[:-len(stop_str)]
    print(outputs)
    return outputs



if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_path", type=str, default="ckpt/GroundingGPT-7B")
    parser.add_argument("--json_path", type=str, default=None)
    parser.add_argument("--video_dir", type=str, default=None)
    parser.add_argument("--output_dir", type=str, default=None)
    parser.add_argument("--temperature", type=float, default=0.99)
    parser.add_argument("--max_new_tokens", type=int, default=2048)
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()
    model_bag = load_pretrained_model(args.model_path)

    import os
    import json 
    args.output_dir = os.path.join(args.output_dir, os.path.basename(os.path.dirname(args.json_path)))
    os.makedirs(args.output_dir, exist_ok=True)
    with open(args.json_path) as f:
        data = json.load(f)
    for i in range(len(data)):
        args.video_file = os.path.join(args.video_dir, data[i]['video'])
        response = single_process(args, model_bag)
        data[i]['response'] = response
    output_file = os.path.basename(args.json_path).replace('.json', '_response.json')
    output_path = os.path.join(args.output_dir, output_file)
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=4)
```

**Comment by cool-xuan** [comment]
I think I have found the problem. I re-trained the model on our data, and I found the output embedding of the Video encoder contains NaN during training.
https://github.com/lzw-lzw/GroundingGPT/blob/1f3f53e5e899b7ae24fe3c8b8bdc803ba66a3f0a/lego/LEGO.py#L450-L495

So, the training is unsuccessful actually.

**Comment by lzw-lzw** [comment]
It seems that there are no issues with your environment and inference code. Could you please check if you have properly prepared the blip2 checkpoint and if the training loss is normal? If you find any problems, please let me know so that we can improve it.

**Comment by cool-xuan** [comment]
> It seems that there are no issues with your environment and inference code. Could you please check if you have properly prepared the blip2 checkpoint and if the training loss is normal? If you find any problems, please let me know so that we can improve it.

We confirm that the blip2 checkpoint is right. There must be something wrong during training. 
We check all tensor if it contains NaN and Inf. 
Only in the first forward process, all tensors are trackable. 
After one  step, the input_embeds are `NaN`.
We check the `input_embeds` in
https://github.com/lzw-lzw/GroundingGPT/blob/1f3f53e5e899b7ae24fe3c8b8bdc803ba66a3f0a/lego/LEGO.py#L367
The logs are as follows:
```
{'loss': 0.8802, 'learning_rate': 6.666666666666665e-08, 'epoch': 0.01}                                                                                                                                                 
  1%|██▌                                                                                                                                                                                 | 1/69 [00:27<31:36, 27.89s/it]In LEGOLlamaModel, Tensor contains NaN
In LM Head, Tensor contains NaN
In LEGOLlamaModel, Tensor contains NaN
In LM Head, Tensor contains NaN
In LEGOLlamaModel, Tensor contains NaN
In LM Head, Tensor contains NaN
In LEGOLlamaModel, Tensor contains NaN
In LM Head, Tensor contains NaN
In LEGOLlamaModel, Tensor contains NaN
In LM Head, Tensor contains NaN
In LEGOLlamaModel, Tensor contains NaN
In LM Head, Tensor contains NaN
{'loss': 0.0, 'learning_rate': 1.333333333333333e-07, 'epoch': 0.03}                                                                                                                                                    
  3%|█████▏                                                                                                                                                                              | 2/69 [00:44<23:42, 21.22s/it]In inputs_embeds, Tensor contains NaN
In inputs_embeds, Tensor contains NaN
In inputs_embeds, Tensor contains NaN
In inputs_embeds, Tensor contains NaN
In inputs_embeds, Tensor contains NaN
In inputs_embeds, Tensor contains NaN
In cur_input_embeds, Tensor contains NaN
In Video Encoder, Tensor contains NaN
In cur_input_embeds, Tensor contains NaN
In Video Encoder, Tensor contains NaN
In cur_input_embeds, Tensor contains NaN
In Video Encoder, Tensor contains NaN
In cur_input_embeds, Tensor contains NaN
In Video Encoder, Tensor contains NaN
In cur_input_embeds, Tensor contains NaN
....
```

**Comment by lzw-lzw** [comment]
I think this might be related to the version of deepspeed. Maybe you can try 'pip install deepspeed==0.9.3' to downgrade the version.

**Comment by cool-xuan** [comment]
Would you mind giving a exact pip list of your environments with all libs and versions.
Maybe some versions of particular libs are conflicting.

**Comment by lzw-lzw** [comment]
Hi, have you tried changing the version of DeepSpeed? In my experience, the issue you mentioned above can be resolved using this approach.

**Comment by cool-xuan** [comment]
> Hi, have you tried changing the version of DeepSpeed? In my experience, the issue you mentioned above can be resolved using this approach.

I have tried, but there is an error when installing deepspeed==0.9.3, like follows:
```
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      /opt/conda/lib/python3.10/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:
      * 'allow_population_by_field_name' has been renamed to 'populate_by_name'
      * 'validate_all' has been renamed to 'validate_default'
        warnings.warn(message, UserWarning)
      /opt/conda/lib/python3.10/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".
      
      You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/setup.py", line 36, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/op_builder/__init__.py", line 18, in <module>
          import deepspeed.ops.op_builder  # noqa: F401
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/__init__.py", line 16, in <module>
          from . import module_inject
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/module_inject/__init__.py", line 6, in <module>
          from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/module_inject/replace_module.py", line 792, in <module>
          from ..pipe import PipelineModule
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/pipe/__init__.py", line 6, in <module>
          from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
          from .module import PipelineModule, LayerSpec, TiedLayerSpec
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/pipe/module.py", line 19, in <module>
          from ..activation_checkpointing import checkpointing
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
          from deepspeed.runtime.config import DeepSpeedConfig
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/config.py", line 29, in <module>
          from .zero.config import get_zero_config, ZeroStageEnum
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/zero/__init__.py", line 6, in <module>
          from .partition_parameters import ZeroParamType
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/zero/partition_parameters.py", line 603, in <module>
          class Init(InsertPostInitMethodToModuleSubClasses):
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/zero/partition_parameters.py", line 605, in Init
          param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
        File "/tmp/pip-install-6ogesugx/deepspeed_3b9faec56316437ca48bd2618937d9ff/deepspeed/runtime/config_utils.py", line 116, in get_config_default
          field_name).required, f"'{field_name}' is a required field and does not have a default value"
      AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?
      Setting ds_accelerator to cuda (auto detect)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
And I didn't find some trackable suggestion to solve this...

**Comment by cool-xuan** [comment]
I just downgrade the pydantic and deepspeed through
```
pip install --upgrade "pydantic<2.0.0"
pip install deepspeed==0.9.3
```
I will try if this solves my issue.

> Hi, have you tried changing the version of DeepSpeed? In my experience, the issue you mentioned above can be resolved using this approach.

**Comment by cool-xuan** [comment]
> I just downgrade the pydantic and deepspeed through
> 
> ```
> pip install --upgrade "pydantic<2.0.0"
> pip install deepspeed==0.9.3
> ```
> 
> I will try if this solves my issue.

@lzw-lzw Following your advice to downgrade deepspeed, the training is working well ! ! ! ! There is no more NaN !!!!
Thanks a lot for your code and model release, and your kind reply.

**Comment by lzw-lzw** [comment]
Glad to see that you have solved the problem. If you have any more questions, feel free to open new issues anytime. If you find our project helpful, please kindly consider giving us a star.
